spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: dengshuai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

zoo:
  guide:
    enable: true
    show-detail: true

logging:
  level:
    com.ideaaedi.zoo: debug