server:
  port: 9527

zoo:
  # 打印组件概览信息
  guide:
    enable: true
    show-detail: true

# Flowable 需要存储数据，需要有数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: dengshuai
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Flowable会开启数据库变更管理工具liquibase， 如果不需要就可以关闭
  liquibase:
    enabled: false

flowable:
  # 当识别到表结构和当前版本不匹配时，是否自动创建或更新数据库表结构
  database-schema-update: true
  # 是否使用异步执行器（如果需要异步执行，建议不要用默认的，而是主动配置对应的异步执行器，详见 https://www.flowable.com/open-source/docs/bpmn/ch05a-Spring-Boot#configuring-async-executors）
  async-executor-activate: false
  # 只使用工作流基础表，其余模块的表不需要生成
  idm.enabled: false
  cmmn.enabled: false
  dmn.enabled: false
  app.enabled: false

# 在zoo-diy-feature-bpmn-by-flowable中已经默认这样配置了
logging:
  level:
    # 将所有实现了org.flowable.common.engine.impl.persistence.entity.Entity的类的日志都打印出debug级别，即可观察到数据库操作日志
    org.flowable.variable.service.impl.persistence.entity: debug
    org.flowable.eventsubscription.service.impl.persistence.entity: debug
    org.flowable.engine.impl.persistence.entity: debug
    org.flowable.batch.service.impl.persistence.entity: debug
    org.flowable.eventregistry.impl.persistence.entity: debug
    org.flowable.identitylink.service.impl.persistence.entity: debug
    org.flowable.entitylink.service.impl.persistence.entity: debug
    org.flowable.app.engine.impl.persistence.entity: debug
    org.flowable.common.engine.impl.persistence.entity: debug
    org.flowable.idm.engine.impl.persistence.entity: debug
    org.flowable.dmn.engine.impl.persistence.entity: debug
    org.flowable.task.service.impl.persistence.entity: debug
    org.flowable.cmmn.engine.impl.persistence.entity: debug
    org.flowable.job.service.impl.persistence.entity: debug
