spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dengshuai

logging:
  level:
    com.ideaaedi.zoo: debug

zoo:
  guide:
    enable: true
    show-detail: true