spring:
  application:
    name: demo

logging:
  level:
    com.ideaaedi.zoo: debug

zoo:
  guide:
    enable: true
    show-detail: true
  msg:
    sms:
      default-sender-id: SmsSenderIdA # 指定默认的短信发送器

# sms4j短信配置
sms:
  config-type: yaml
  blends:
    alibaba: # 所属供应商
      SmsSenderIdA: # 短信发送器唯一标识（sms4j的config-id）
        ###### 当前短信发送器的相关配置（更多详见官网） ######
        #有些称为accessKey有些称之为apiKey，也有称为sdkKey或者appId。
        access-key-id: 您的accessKey
        #称为accessSecret有些称之为apiSecret。
        access-key-secret: 您的accessSecret
        #您的短信签名, 即"【xxx】你的验证码..."中的xxx
        signature: 程序开发学习使用
        #模板ID 如果不需要简化的sendMessage方法可以不配置
        template-id: SMS_471375016
        # 随机权重，负载均衡的权重值依赖于此，默认为1，如不需要负载均衡可不进行配置
        #weight: 1
        #短信自动重试间隔时间  默认五秒
        #retry-interval: 5
        # 短信重试次数，默认0次不重试，如果你需要短信重试则根据自己的需求修改值即可
        #max-retries: 0
        # 当前厂商的发送数量上限，默认不设置上限
        #maximum: 10000
        # 自定义实现工厂路径
        #factory: {BaseProviderFactory实现类的全类名}
        ###### 阿里云的个性化配置（更多详见官网） ######
        # 默认即为 dysmsapi.aliyuncs.com，见org.dromara.sms4j.aliyun.config.AlibabaConfig
        requestUrl: "dysmsapi.aliyuncs.com"
        # 默认即为 SendSms，见org.dromara.sms4j.aliyun.config.AlibabaConfig
        action: "SendSms"
        # 默认即为 2017-05-25，见org.dromara.sms4j.aliyun.config.AlibabaConfig
        version: "2017-05-25"
        # 默认即为 cn-hangzhou，见org.dromara.sms4j.aliyun.config.AlibabaConfig
        regionId: "cn-hangzhou"

